# 站点微缩图
favicon: /images/favicon.ico

# 评论 https://giscus.app/zh-CN
giscus:
  enable: true
  repo: 0914xc/weixiaochen-blog
  repo_id: R_kgDOHKKVwg
  category: Announcements
  category_id: DIC_kwDOHKKVws4CPB45
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  input_position: top
  theme: light
  lang: zh-CN
  loading: lazy
  crossorigin: anonymous
